version: '{branch}.{build}'
branches:
  only:
  - master
skip_tags: true
clone_depth: 3
cache: C:\Users\appveyor\.gradle
build_script:
- cmd: gradlew.bat build --info --no-daemon
test_script:
- cmd: gradlew.bat check --info --no-daemon
